namespace EfExtensions.Core.Interfaces.Model;

/// <summary>
/// Base class for Ef Models.
/// Contains an autogenerated primary key and a non mapped operation type.
/// </summary>
/// <typeparam name="T">Primary key type.</typeparam>
public interface IDbItem<T> : IHasOperation
{
    /// <summary>
    /// Primary key.
    /// </summary>
    public T Id { get; set; }
}